export const PRESUPUESTO_GRUPOS = ['tren_delantero', 'tren_trasero', 'frenos', 'cubierta'] as const;

export const PRESUPUESTO_GRUPO_LABELS: Record<string, string> = {
  tren_delantero: 'Tren delantero',
  tren_trasero: 'Tren trasero',
  frenos: 'Frenos',
  cubierta: 'Cubiertas',
};

export const PRESUPUESTO_ITEMS: Record<string, readonly string[]> = {
  tren_delantero: [
    'Juego de Bujes',
    'Bujes Tensor',
    'Bujes Barra Estabiliz.',
    'Bieleta Barra Estabiliz.',
    'Rótulas',
    'Extremos de Dirección',
    'Axiales',
    'Caja de Dirección',
    'Guardapolvos de Dirección',
    'Junta de Homocinética',
    'Guardapolvos Junta Homoc.',
    'Rodamientos de Ruedas',
    'Semiejes',
    'Amortiguadores Delanteros',
    'Parrilla Superior',
    'Parrilla Inferior',
    'Barra Estabilizadora',
    'Cazoleta Amortiguador',
    'Crapodina Amortiguador',
    'Espirales',
    'Base Espireles',
    'Falso Brazo',
    'Brazo Pitman',
  ],
  tren_trasero: [
    'Amortiguadores Traseros',
    'Bujes Suspensión',
    'Parrillas',
    'Bujes Tensores',
    'Elásticos',
    'Bujes Barra Estabilizadora',
    'Espirales',
  ],
  frenos: [
    'Juego de Pastillas',
    'Rectificado de Discos',
    'Rectificado de Campanas',
    'Encintado de Patines',
    'Discos',
    'Cilindros',
    'Cubetas',
    'Guardapolvos',
    'Bomba de Frenos',
    'Reparación de Servo',
    'Líquido de Freno',
    'Mano de Obra',
  ],
  cubierta: [
    'Fate',
    'Continental',
    'Michelin',
    'General Tire',
    'BF Goodrich',
    'Cámaras',
    'Balanceos Autos',
    'Balanceos Cmta.',
    'Alineado',
    'Nitrógeno',
    'Antióxido',
    'Parches',
    'Seguros de Neumáticos',
    'Rotación',
    'Mano de Obra',
    'Varios',
    'Corrección de comba',
  ],
};

export type PresupuestoGrupoKey = keyof typeof PRESUPUESTO_ITEMS;
